name: Release

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'master'

jobs:
  buildPlugin:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Release plugin
        run: ./gradlew :plugin:publish -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

  buildLib:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Release grpc-multiplatform-lib
        run: ./gradlew :grpc-multiplatform-lib:publish -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}